# Generated by Django 4.2 on 2024-10-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expenseowedby',
            index=models.Index(fields=['userId'], name='expenses_ex_userId__adb882_idx'),
        ),
        migrations.AddIndex(
            model_name='expensepaidby',
            index=models.Index(fields=['userId'], name='expenses_ex_userId__60e588_idx'),
        ),
    ]
